# Generated by Django 3.0.7 on 2020-06-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_cod', models.IntegerField()),
                ('cli_nom', models.CharField(max_length=20)),
                ('cli_apell', models.CharField(max_length=20)),
                ('cli_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_cod', models.IntegerField()),
                ('dep_nom', models.CharField(max_length=20)),
                ('dep_tel', models.IntegerField()),
                ('dep_ubica', models.CharField(max_length=5)),
                ('dep_mod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tra_cod', models.IntegerField()),
                ('tra_nom', models.CharField(max_length=20)),
                ('tra_apell', models.CharField(max_length=20)),
                ('tra_tel', models.IntegerField()),
                ('tra_cargo', models.CharField(max_length=20)),
                ('tra_sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ven_codp', models.IntegerField()),
                ('ven_nom', models.CharField(max_length=20)),
                ('ven_descrip', models.CharField(max_length=20)),
                ('ven_costo', models.IntegerField()),
            ],
        ),
    ]
